### ISSUE TITLE
Could not resolve "@vue/composition-api/dist/vue-composition-api.esm.js" in @vue/apollo-composable

### ISSUE THREAD

**Issue by masterkain** [Akryum/vue-apollo#1263]
not sure what happened but since https://github.com/vuejs/vue-apollo/commit/f4e2a14bba632855ca49a59ee50b8e75eeec6df4

in a vue 3 project I get:

```
dashboard_1         |  > node_modules/vue-demi/lib/index.mjs:2:30: error: Could not resolve "@vue/composition-api/dist/vue-composition-api.esm.js" (mark it as external to exclude it from the bundle)
dashboard_1         |     2 │ ...sitionAPI from '@vue/composition-api/dist/vue-composition-api.esm.js'
dashboard_1         |       ╵                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
dashboard_1         |
dashboard_1         | error when starting dev server:
dashboard_1         | Error: Build failed with 1 error:
dashboard_1         | node_modules/vue-demi/lib/index.mjs:2:30: error: Could not resolve "@vue/composition-api/dist/vue-composition-api.esm.js" (mark it as external to exclude it from the bundle)
dashboard_1         |     at failureErrorWithLog (/usr/src/app/node_modules/esbuild/lib/main.js:1478:15)
dashboard_1         |     at /usr/src/app/node_modules/esbuild/lib/main.js:1136:28
dashboard_1         |     at runOnEndCallbacks (/usr/src/app/node_modules/esbuild/lib/main.js:926:63)
dashboard_1         |     at buildResponseToResult (/usr/src/app/node_modules/esbuild/lib/main.js:1134:7)
dashboard_1         |     at /usr/src/app/node_modules/esbuild/lib/main.js:1243:14
dashboard_1         |     at /usr/src/app/node_modules/esbuild/lib/main.js:614:9
dashboard_1         |     at handleIncomingPacket (/usr/src/app/node_modules/esbuild/lib/main.js:711:9)
dashboard_1         |     at Socket.readFromStdout (/usr/src/app/node_modules/esbuild/lib/main.js:581:7)
dashboard_1         |     at Socket.emit (node:events:394:28)
dashboard_1         |     at Socket.emit (node:domain:475:12)
dashboard_1         | error Command failed with exit code 1.
```

```
"@apollo/client": "^3.4.13",
"@vue/apollo-composable": "^4.0.0-alpha.14",
"@vue/apollo-util": "^4.0.0-alpha.14",
"vue": "^3.2.13",


"@vue/apollo-composable@^4.0.0-alpha.14":
  version "4.0.0-alpha.15"
  resolved "https://registry.yarnpkg.com/@vue/apollo-composable/-/apollo-composable-4.0.0-alpha.15.tgz#4a93417cb112cc1ad9c8fbdf47008909f71fca5b"
  integrity sha512-c/xk/po4nTcAnwIG+ZK0XFwY84BiKJquGnK2T+qolp0Saeb5amoTtHu6CEZ6Xd635otqUTY8SODOoFraoAttNQ==
  dependencies:
    throttle-debounce "^3.0.1"
    ts-essentials "^8.1.0"
    vue-demi "^0.11.4"
```

**Comment by masterkain** [comment]
https://github.com/vueuse/vue-demi/commit/98185abe64ed3301721db90e711f8bafb7529b57

**Comment by masterkain** [comment]
maybe we need to add peerDependencies in package.json as per vue-demi readme?

```
{
  "dependencies": {
    "vue-demi": "latest"
  },
  "peerDependencies": {
    "@vue/composition-api": "^1.0.0-rc.1",
    "vue": "^2.0.0 || >=3.0.0"
  },
  "peerDependenciesMeta": {
    "@vue/composition-api": {
      "optional": true
    }
  },
  "devDependencies": {
    "vue": "^3.0.0" // or "^2.6.0" base on your preferred working environment
  },
}
```

https://github.com/vueuse/vue-demi/issues/79#issuecomment-922249136
