### ISSUE TITLE
Error on successful query

### ISSUE THREAD

**Issue by R0N1n-dev** [Akryum/vue-apollo#1371]
**Describe the bug**
```vue.runtime.esm.js:619 [Vue warn]: Error in created hook: "TypeError: Cannot read properties of undefined (reading 'categories')"

found in

---> <AboutView> at src/views/AboutView.vue
       <App> at src/App.vue
         <Root>
warn @ vue.runtime.esm.js:619
logError @ vue.runtime.esm.js:1893
globalHandleError @ vue.runtime.esm.js:1888
handleError @ vue.runtime.esm.js:1848
invokeWithErrorHandling @ vue.runtime.esm.js:1871
callHook @ vue.runtime.esm.js:4235
Vue2._init @ vue.runtime.esm.js:5022
VueComponent @ vue.runtime.esm.js:5168
createComponentInstanceForVnode @ vue.runtime.esm.js:3304
init @ vue.runtime.esm.js:3133
merged @ vue.runtime.esm.js:3322
createComponent2 @ vue.runtime.esm.js:6022
createElm @ vue.runtime.esm.js:5969
updateChildren @ vue.runtime.esm.js:6260
patchVnode @ vue.runtime.esm.js:6363
patch2 @ vue.runtime.esm.js:6526
Vue2._update @ vue.runtime.esm.js:3963
updateComponent @ vue.runtime.esm.js:4081
get @ vue.runtime.esm.js:4495
run @ vue.runtime.esm.js:4570
flushSchedulerQueue @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
flushCallbacks @ vue.runtime.esm.js:1915
Promise.then (async)
timerFunc @ vue.runtime.esm.js:1942
nextTick @ vue.runtime.esm.js:1999
queueWatcher @ vue.runtime.esm.js:4418
update @ vue.runtime.esm.js:4560
notify @ vue.runtime.esm.js:730
reactiveSetter @ vue.runtime.esm.js:1055
(anonymous) @ vue-router.esm.js:3003
(anonymous) @ vue-router.esm.js:3002
updateRoute @ vue-router.esm.js:2414
(anonymous) @ vue-router.esm.js:2263
(anonymous) @ vue-router.esm.js:2402
step @ vue-router.esm.js:2001
step @ vue-router.esm.js:2008
runQueue @ vue-router.esm.js:2012
(anonymous) @ vue-router.esm.js:2397
step @ vue-router.esm.js:2001
(anonymous) @ vue-router.esm.js:2005
(anonymous) @ vue-router.esm.js:2384
(anonymous) @ vue-router.esm.js:2127
(anonymous) @ vue-router.esm.js:2203
Promise.then (async)
(anonymous) @ vue-router.esm.js:2150
(anonymous) @ vue-router.esm.js:2171
(anonymous) @ vue-router.esm.js:2171
flatMapComponents @ vue-router.esm.js:2170
(anonymous) @ vue-router.esm.js:2106
iterator @ vue-router.esm.js:2362
step @ vue-router.esm.js:2004
step @ vue-router.esm.js:2008
runQueue @ vue-router.esm.js:2012
confirmTransition @ vue-router.esm.js:2392
transitionTo @ vue-router.esm.js:2260
init @ vue-router.esm.js:2994
beforeCreate @ vue-router.esm.js:1298
invokeWithErrorHandling @ vue.runtime.esm.js:1863
callHook @ vue.runtime.esm.js:4235
Vue2._init @ vue.runtime.esm.js:5018
Vue @ vue.runtime.esm.js:5099
mount @ vue-composition-api.mjs:1634
(anonymous) @ main.js?t=1655203351753:26
vue.runtime.esm.js:1897 TypeError: Cannot read properties of undefined (reading 'categories')
    at VueComponent.update (AboutView.vue:25:1)
    at exports.reapply (vue-apollo.esm.js:452:25)
    at DollarApollo2.addSmartQuery (vue-apollo.esm.js:1415:26)
    at VueComponent.launch (vue-apollo.esm.js:2049:34)
    at invokeWithErrorHandling (vue.runtime.esm.js:1863:57)
    at callHook (vue.runtime.esm.js:4235:7)
    at VueComponent.Vue2._init (vue.runtime.esm.js:5022:5)
    at new VueComponent (vue.runtime.esm.js:5168:12)
    at createComponentInstanceForVnode (vue.runtime.esm.js:3304:10)
    at init (vue.runtime.esm.js:3133:45)
```

code
```
<template>
  <div class="about">
    <h1>This is an about page</h1>
    <div v-if="categories.length > 0">{{categories}}</div>
  </div>
</template>

<script>
import gql from "graphql-tag"
export default {
  data:()=>({
    categories: []
  }),
  apollo:{
    categories: gql `query {
      categories{
        posts{
          slug
          category{
            name
          }
        }
      }
    }`,
    update: data => data.categories,
  }
}
</script>

<style>
@media (min-width: 1024px) {
  .about {
    min-height: 100vh;
    display: flex;
    align-items: center;
  }
}
</style>
```

**To Reproduce**
1. Create vite2 project with "npm init vue@2" and install dependancies
2. install vue-apollo using simple apollo-boost method on documentation page  and setup as docs show
3. Added uri for my backend data source
4. Ran "npm run dev" to start server and added query.

**Expected behavior**
Results of query displayed with no errors.
Should not be getting errors with successful query if even the data is being displayed.
Query is successful but error show regardless.
But The error is displayed first.Regardless of a successful query, then the results appear

**Versions**
     "apollo-boost": "^0.4.9",
    "graphql": "^15.8.0",
    "vue": "^2.6.14",
    "vue-apollo": "^3.1.0",

**Additional context**
I have run into weird errors with "Apollo"  before especially because of documentation not being updated appropriately or just missing integral code for an example.
Not sure if this is that, but would not be surprised if is the case.

**Comment by Akryum** [comment]
Here is the docs you are looking for: https://apollo.vuejs.org/guide/apollo/queries.html#name-matching

**Comment by Akryum** [comment]
You code should be:

```js
import gql from "graphql-tag"
export default {
  data:()=>({
    categories: []
  }),
  apollo:{
    categories: {
      query: gql `query {
        categories{
          posts{
            slug
            category{
              name
            }
          }
        }
      }`,
      update: data => data.categories,
    }
  }
}
```

**Comment by Akryum** [comment]
But since you have `categories` as the root field in your query and you have named the component data prop `categories`, you don't need to use the `update` option as vue-apollo will automatically pick the data if it has the same name.
