### ISSUE TITLE
Nuxt3/Vite error when importing Apollo/ApolloClient

### ISSUE THREAD

**Issue by rylanharper** [Akryum/vue-apollo#1406]
**Describe the bug**
Hey there! I have been developing headless shopify stores with Vue and `graphql-request` for a while now and and trying out Nuxt3 with Apollo to see if I can make use of some of its features. Anyway, I have the following error in my terminal and I cannot find the issue for the life of me:
```
[nuxt] [request error] [unhandled] [500] __vite_ssr_import_1__.setVerbosity is not a function
  at ./node_modules/@apollo/client/core/index.js:48:23
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:217:5)
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:113:12)
  at async request (./node_modules/vite-node/dist/client.mjs:136:16)
  at async ./plugins/apollo-client.ts:3:31
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:217:5)
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:113:12)
  at async request (./node_modules/vite-node/dist/client.mjs:136:16)
```

I have gone through all the checks to set up my Nuxt3 project in a way that others have done in the past and transpiling my `@apollo/client`, `@vue/apollo-composable`, `ts-invariant/process`:

`nuxt.config.js`
```
import { defineNuxtConfig } from 'nuxt'

export default defineNuxtConfig({
  runtimeConfig: {
    public: {
      apiToken: process.env.STOREFRONT_API_ACCESS_TOKEN || '',
      apiEndpoint: process.env.STOREFRONT_API_ENDPOINT || ''
    }
  },

  build: {
    transpile: [
      '@apollo/client',
      '@vue/apollo-composable',
      'ts-invariant/process'
    ]
  }  
})
```

I also have created a proper `plugin` for apollo:
```
import { ApolloClient, InMemoryCache, createHttpLink } from '@apollo/client/core'
import { DefaultApolloClient, provideApolloClient } from '@vue/apollo-composable'

export default defineNuxtPlugin((nuxtApp) => {
  const lang = 'en-US'
  const config = useRuntimeConfig()

  // Shopify Client
  const shopifyClient = new ApolloClient({
    cache: new InMemoryCache(),
    link: createHttpLink({
      credentials: 'omit',
      uri: config.public.aipEndpoint,
      headers: {
        'X-Shopify-Storefront-Access-Token': config.public.apiToken,
        'Accept-Language': lang,
        'Content-Type': 'application/json',
      },
    }),
    ssrMode: process.server
  })

  // Provide Apollo Clients
  provideApolloClient(shopifyClient);
  nuxtApp.provide('apollo', { DefaultApolloClient, shopifyClient })
})
```

However the error still persists. I am not sure if this is a Nuxt3 issue or an issue with the latest version of Apollo. Perhaps I am creating the plugin incorrectly? It seems unlikely as others have created the exact same plugin for starter projects I am referencing such as NuxtShop, etc. 

**To Reproduce**
1. Create a new Nuxt3 app: `npx nuxi init nuxt-app` → `yarn install`
2. Install the proper packages for apollo: yarn add → `@apollo/client`, `@vue/apollo-composable`, `apollo-cache-inmemory`, `graphql`, `graphql-tag`
3. Create a similar `nuxt.config.ts` and `apollo-client.ts` file like I have shown (you need an `.env` variables). However this error also occurs with a standard graphql query such as the follow `apollo-client.ts` file:
```
import { DefaultApolloClient } from "@vue/apollo-composable";
import {
  ApolloClient,
  createHttpLink,
  InMemoryCache,
} from "@apollo/client/core";

export default defineNuxtPlugin((app) => {
  const httpLink = createHttpLink({
    uri: "https://rickandmortyapi.com/graphql",
  });

  const cache = new InMemoryCache();

  const apolloClient = new ApolloClient({
    link: httpLink,
    cache,
  });

  app.vueApp.provide(DefaultApolloClient, apolloClient);
});
```
4. Run `yarn dev` → Error occurs

**Expected behavior**
Apollo should import just fine without flagging terminal errors. The plugin should properly merge with a Nuxt3 dev environment.

**Versions**
Here is my `package.json`
```
  "devDependencies": {
    "nuxt": "3.0.0-rc.8"
  },
  "dependencies": {
    "@apollo/client": "^3.6.9",
    "@vue/apollo-composable": "^4.0.0-alpha.19",
    "apollo-cache-inmemory": "^1.6.6",
    "graphql": "^16.6.0",
    "graphql-tag": "^2.12.6"
  }
```

**Additional context**
I am not sure if this a Nuxt3 issue or Apollo issue.

**Comment by rylanharper** [comment]
Using `pnpm` solves this issue
