### ISSUE TITLE
Unhandled GraphQL subscription error TypeError: _this.client.subscribe is not a function

### ISSUE THREAD

**Issue by ottolauncher** [Akryum/vue-apollo#1487]
**Using subscribeToMore from useQuery**
Unhandled GraphQL subscription error TypeError: _this.client.subscribe is not a function
Hello Sir thank you for your hard work, sorry to bother but this error keep coming when i try to use subscriptions, but the rest( Mutations, Queries) are just fine. Only the subscriptions have that specifically on subscribeToMore function. Maybe it's my bad...and I apologize for that but any tips would be great. Have a nice one 

**To Reproduce**

```

// graphql-ws.js
import {print} from 'graphql';
import {ApolloLink, Observable} from '@apollo/client';
import {createClient} from "graphql-ws";

class WebSocketLink extends ApolloLink {
    client;

    constructor(options) {
        super();
        this.client = createClient(options);
    }

    request(operation) {
        return new Observable((sink) => {
            console.log({ ...operation, query: print(operation.query) });
            return this.client.subscribe(
                {...operation, query: print(operation.query)},
                {
                    next: sink.next.bind(sink),
                    complete: sink.complete.bind(sink),
                    error: (err) => {
                        if (err instanceof Error) {
                            return sink.error(err);
                        }

                        if (err instanceof CloseEvent) {
                            return sink.error(
                                // reason will be available on clean closes
                                new Error(
                                    `Socket closed with event ${err.code} ${err.reason || ''}`,
                                ),
                            );
                        }

                        return sink.error(
                            new Error(
                                err
                                    .map(({message}) => message)
                                    .join(', '),
                            ),
                        );
                    },
                },
            );
        });
    }
}

export default WebSocketLink

// client.js
...
import {ApolloClient, InMemoryCache, HttpLink, split} from '@apollo/client/core'
import {GraphQLWsLink} from "@apollo/client/link/subscriptions";
import GraphQLWebSocketLink from './graphql-ws'
...
let subscriptionLink;

if (import.meta.env.REACT_APP_SSE_PROTOCOL) {
    subscriptionLink = new SSELink({url: uri})
} else if (import.meta.env.REACT_APP_WS_PROTOCOL === 'graphql-transport-ws') {
    subscriptionLink = new GraphQLWebSocketLink({
        url: wsURI,
    })
} else {
    subscriptionLink = new GraphQLWsLink({
        uri: wsURI,
        options: {
            reconnect: true
        }
    })
}
...
const httpLink = new HttpLink({uri})
...
const link = split(
    ({query}) => {
        const {kind, operation}  = getMainDefinition(query)
        return kind === 'OperationDefinition' &&  operation === 'subscription'
    },
    subscriptionLink,
    httpLink,
    errorLink,
)
...
export const apolloClient = new ApolloClient({
    cache,
    link,
})

// App.vue
...
const {result: channelResult, loading: channelLoading, error: channelError, subscribeToMore} = useQuery(CHANNELS_QUERY)
  subscribeToMore(() => ({
    document: CHANNEL_ADDED,
    updateQuery: (prev, {subscriptionData}) => {
      if (!subscriptionData.data) return prev
      const newChannel = subscriptionData.data.channelAdded;
      if (prev.allChannels.find((c) => c.id === newChannel.id)) return prev
      return Object.assign({}, prev, {allChannels: [newChannel, ...prev]})
    }
  }))
...

// main.js
...
import {DefaultApolloClient} from '@vue/apollo-composable'
...
import {apolloClient} from "./apollo/client.js";
...

const app = createApp({
    setup() {
        provide(DefaultApolloClient, apolloClient)
    },
    render: () => h(App)
})
...
app.mount('#app')
```
Then the console error
```
Unhandled GraphQL subscription error TypeError: _this.client.subscribe is not a function
    at index.ts:55:26
    at new Subscription2 (module.js:190:34)
    at Observable2.subscribe (module.js:264:12)
    at Object.complete (Concast.ts:219:28)
    at Concast2.start (Concast.ts:107:19)
    at new Concast2 (Concast.ts:84:12)
    at QueryManager2.getObservableFromLink (QueryManager.ts:1049:21)
    at makeObservable (QueryManager.ts:925:13)
    at QueryManager2.startGraphQLSubscription (QueryManager.ts:974:4)
    at ObservableQuery2.subscribeToMore (ObservableQuery.ts:520:8)
```

**Expected behavior**
The usual behavior as on the documention [vue-apollo](https://v4.apollo.vuejs.org/guide-composable/subscription.html#subscribetomore)

**Versions**
vue:"^3.2.47"
vue-apollo:"^4.0.0-beta.7"
@apollo/client:"^3.7.16"

**Additional context**
Trying to consume subscriptions using vue apollo and apollo client

**Comment by ottolauncher** [comment]
It working now!!!
I've make the changes bellow
`let subscriptionLink = new GraphQLWsLink(createClient({url: wsURI, options: {reconnect: true}}))`
