### ISSUE TITLE
Conflict when using ApolloSSR.prefetchAll()

### ISSUE THREAD

**Issue by negezor** [Akryum/vue-apollo#378]
I update the apollo-module module under vue-apollo to v3.0.0-beta.20. I ran into the fact that when ApolloSSR.prefetchAll() is called, it conflicts with other modules that need a main VM. Nuxt.js error:
```
 TypeError: _vm._ssrStyle is not a function
  at Object.render (pages_releases_index.js:374:21)
  at Promise (C:\Users\negezor\projects\test-conflict\node_modules\vue-apollo\ssr\index.js:54:24)
  at new Promise (<anonymous>)
  at walkTree (C:\Users\negezor\projects\test-conflict\node_modules\vue-apollo\ssr\index.js:26:10)
  at Promise.all.components.map.component (C:\Users\negezor\projects\test-conflict\node_modules\vue-apollo\ssr\index.js:20:33)
  at Array.map (<anonymous>)
  at Object.exports.getQueriesFromTree (C:\Users\negezor\projects\test-conflict\node_modules\vue-apollo\ssr\index.js:20:16)
  at Object.exports.prefetchAll (C:\Users\negezor\projects\test-conflict\node_modules\vue-apollo\ssr\index.js:11:18)
  at beforeNuxtRender (server-bundle.js:2310:67)
  at promisify (server-bundle.js:3874:15)
  at Promise.all.ssrContext.beforeRenderFns.map.fn (server-bundle.js:3303:116)
  at Array.map (<anonymous>)
  at beforeRender (server-bundle.js:3303:50)
  at module.exports.../website/app/.nuxt/server.js.__webpack_exports__.default (server-bundle.js:3479:9)
```

**Comment by Arkagami** [comment]
Hi, Negezor))

**Comment by ciscorn** [comment]
I think this error occurs when there are attributes like `:class={'is-active': dataA}`, `:style={color: dataB}`,  etc on the component template.

**Comment by negezor** [comment]
This has not been fixed, as before, when the function is used, fatal errors occur on the components.
```
TypeError: Cannot read property '$ssrContext' of undefined
 at Component.options.data (website/app/.nuxt/utils.js:34:0)
 at createFakeInstance (C:\Users\negezor\projects\test-conflict\node_modules\vue-apollo\ssr\index.js:148:23)
 at Promise (C:\Users\negezor\projects\test-conflict\node_modules\vue-apollo\ssr\index.js:32:16)
 at new Promise (<anonymous>)
 at walkTree (C:\Users\negezor\projects\test-conflict\node_modules\vue-apollo\ssr\index.js:30:10)
 at Promise.all.components.map.component (C:\Users\negezor\projects\test-conflict\node_modules\vue-apollo\ssr\index.js:24:33)
 at Array.map (<anonymous>)
 at Object.exports.getQueriesFromTree (C:\Users\negezor\projects\test-conflict\node_modules\vue-apollo\ssr\index.js:24:16)
 at Object.exports.prefetchAll (C:\Users\negezor\projects\test-conflict\node_modules\vue-apollo\ssr\index.js:15:18)
 at beforeNuxtRender (website/app/.nuxt/apollo-module.js:94:0)
 at promisify (website/app/.nuxt/utils.js:232:0)
 at Promise.all.ssrContext.beforeRenderFns.map.fn (website/app/.nuxt/server.js:80:0)
 at Array.map (<anonymous>)
 at beforeRender (website/app/.nuxt/server.js:80:0)
 at module.exports.../website/app/.nuxt/server.js.__webpack_exports__.default (website/app/.nuxt/server.js:256:0)
 at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by Akryum** [comment]
Do you have a reproduction to share?

**Comment by negezor** [comment]
Of course, here's the simplest [example](https://github.com/negezor/nuxt-edge-vue-apollo-error).

**Comment by Akryum** [comment]
Fixed in latest beta.
