### ISSUE TITLE
FetchMore calling backend twice and ObservableQuery with this id doesn't exist: 7

### ISSUE THREAD

**Issue by guilhermewaess** [Akryum/vue-apollo#636]
Hello, I'm doing this project to learn a bit more about graphQL 
But during the implementation of FetchMore, I'm struggling with this error: 

```
Uncaught (in promise) Invariant Violation: ObservableQuery with this id doesn't exist: 7
    at new InvariantError (webpack-internal:///./node_modules/ts-invariant/lib/invariant.esm.js:17:28)
    at invariant (webpack-internal:///./node_modules/ts-invariant/lib/invariant.esm.js:29:15)
    at QueryManager.getQueryWithPreviousResult (webpack-internal:///./node_modules/apollo-client/bundle.esm.js:1542:96)
    at ObservableQuery.updateQuery (webpack-internal:///./node_modules/apollo-client/bundle.esm.js:330:31)
    at eval (webpack-internal:///./node_modules/apollo-client/bundle.esm.js:250:19)
```

After investigating a while, I saw that graphql is hitting the backend twice when I click on showMore button
First with old variables, then with updated variables

Here is the VUE component

```
<template>
  <v-container text-xs-center
               v-if="infiniteScrollPosts">
    <div v-for="(post, index) in infiniteScrollPosts.posts"
         :key="index">
      <img :src="post.imgUrl"
           height="100px">
      <h3>{{ post.title }}</h3>
    </div>

    <v-btn flat
           @click="showMorePosts"
           v-if="showMoreEnabled">Fetch More</v-btn>
  </v-container>
</template>

<script>
import INFINITE_SCROLL_POSTS from '../../queries/infiniteScrollPosts.gql';

export default {
  name: 'Posts',
  data() {
    return {
      pagination: {
        pageNum: 1,
        pageSize: 1,
      },
      showMoreEnabled: true,
    };
  },
  apollo: {
    infiniteScrollPosts: {
      query: INFINITE_SCROLL_POSTS,
      variables() {
        return {
          pagination: {
            pageNum: this.pagination.pageNum,
            pageSize: this.pagination.pageSize,
          },
        };
      },
    },
  },
  methods: {
    showMorePosts() {
      this.pagination.pageNum += 1;
      // Fetch more data and transform the original result
      this.$apollo.queries.infiniteScrollPosts.fetchMore({
        // New variables
        variables() {
          return {
            pagination: {
              pageNum: this.pagination.pageNum,
              pageSize: this.pagination.pageSize,
            },
          };
        },
        // Transform the previous result with new data
        updateQuery: (previousResult, { fetchMoreResult }) => {
          const newPosts = fetchMoreResult.infiniteScrollPosts.posts;
          const { hasMore } = fetchMoreResult.infiniteScrollPosts;

          this.showMoreEnabled = hasMore;

          return {
            infiniteScrollPosts: {
              __typename: previousResult.infiniteScrollPosts.__typename, // eslint-disable-line
            
              posts: [...previousResult.infiniteScrollPosts.posts, ...newPosts],
              hasMore,
            },
          };
        },
      });
    },
  },
};
</script>

```

Here the network when I hit showMore button:
The two last requests are made by fetchMore
![image](https://user-images.githubusercontent.com/5339165/58656522-b9bcec80-831c-11e9-82dd-d516f200ba9e.png)

The first one contains old variables
![image](https://user-images.githubusercontent.com/5339165/58656622-f1c42f80-831c-11e9-8045-60621fc22754.png)

The second one contains the updated variables
![image](https://user-images.githubusercontent.com/5339165/58656661-00aae200-831d-11e9-9fcd-7bed2b7704d3.png)

**Comment by guilhermewaess** [comment]
Ok, my bad.

The problem was the variables property <- on the first call it should be an object otherwise every time that this.pagination.numPage changes, it will trigger the query again.

**Comment by goodking-bq** [comment]
i have same problem,but pagenation work well.
i don't know how to fix

**Comment by guilhermewaess** [comment]
@goodking-bq can you paste the code here? perhaps I can help you.

**Comment by goodking-bq** [comment]
@guilhermewaess thanks befor .
this is my code:
```vue
<template>
  <div class="app-container">
    <el-form :inline="true" v-model="searchForm" class="demo-form-inline" size="small">
      <template v-for="header in headers">
        <el-form-item :label="header.name" :key="header.value" v-if="header.searchable">
          <el-input :placeholder="header.name" v-model.lazy="$data['searchForm'][header.value]" />
        </el-form-item>
      </template>
    </el-form>
    <el-table :data="tableData" border size="small">
      <template v-for="header in headers">
        <el-table-column
          v-bind:key="header.value"
          :prop="header.value"
          :label="header.name"
          :width="header.width"
        ></el-table-column>
      </template>
    </el-table>
    <div class="block push4" style="margin-top: 20px">
      <el-row :gutter="10">
        <el-col :span="6" :offset="6">
          <el-pagination
            background
            @size-change="handleSizeChange"
            @current-change="handlePageChange"
            :current-page.sync="page"
            :page-sizes="[20, 50, 100, 200]"
            :page-size="pageSize"
            layout="sizes, prev, pager, next,total"
            :total="totalCount"
          ></el-pagination>
        </el-col>
      </el-row>
    </div>
  </div>
</template>
<script>
import platformList from "./graphql/platform.graphql";
export default {
  name: "SmartTable",
  props: {
    objType: {
      type: String,
      required: true
    },
    headers: {
      type: Array,
      required: true
    }
  },
  data() {
    return {
      formInline: { user: "", region: "" },
      dataList: [],
      tableData: [],
      totalCount: 0,
      page: 1,
      pageSize: 20,
      searchForm: { name: "", enName: "xi" }
    };
  },
  mounted() {
    this.$nextTick(function() {});
  },
  computed: {
    variables() {
      return {
        limit: this.pageSize,
        offset: this.pageSize * (this.page - 1),
        filters: Object.keys(this.searchForm).map(item => {
          return {
            key: item.replace(/([A-Z])/g,"_$1").toLowerCase(),
            op: "contains",
            val: this.searchForm[item]
          };
        })
      };
    }
  },
  watch: {
    searchForm: {
      handler(val, oldVal) {
        this.searchForm = val;
        this.$apollo.queries.dataList.fetchMore({
          variables() {
            return this.variables;
          },
          updateQuery: (previousResult, { fetchMoreResult }) => {
            return {
              platformList: {
                __typename: previousResult.platformList.__typename,
                edges: [...fetchMoreResult.platformList.edges],
                totalCount: previousResult.platformList.totalCount
              }
            };
          }
        });
      },
      deep: true
    }
  },
  apollo: {
    dataList: {
      query: platformList,
      variables() {
        return this.variables;
      },
      manual: true,
      update: data => data.platformList,
      result({ data, loading, networkStatus }) {
        this.totalCount = data.platformList.totalCount;
        this.tableData = data.platformList.edges.map(item => {
          return item.node;
        });
      }
    }
  },
  methods: {
    handleSizeChange(val) {
      this.pageSize = val;
      console.log(this.pageSize);
      this.$apollo.queries.dataList.fetchMore({
        variables() {
          return this.variables;
        },
        updateQuery: (previousResult, { fetchMoreResult }) => {
          return {
            platformList: {
              __typename: previousResult.platformList.__typename,
              edges: [...fetchMoreResult.platformList.edges],
              totalCount: previousResult.platformList.totalCount
            }
          };
        }
      });
    },
    handlePageChange(val) {
      this.$apollo.queries.dataList.fetchMore({
        variables() {
          return this.variables;
        },
        updateQuery: (previousResult, { fetchMoreResult }) => {
          return {
            platformList: {
              __typename: previousResult.platformList.__typename,
              edges: [...fetchMoreResult.platformList.edges],
              totalCount: previousResult.platformList.totalCount
            }
          };
        }
      });
    }
  }
};
</script>
```
every time ,i change pageSize or  searchForm ,raise this error :
```
invariant.esm.js?a957:12 Uncaught (in promise) Invariant Violation: ObservableQuery with this id doesn't exist: 87
    at new InvariantError (webpack-internal:///./node_modules/ts-invariant/lib/invariant.esm.js:17:28)
    at invariant (webpack-internal:///./node_modules/ts-invariant/lib/invariant.esm.js:29:15)
    at QueryManager.getQueryWithPreviousResult (webpack-internal:///./node_modules/apollo-client/bundle.esm.js:1549:96)
    at ObservableQuery.updateQuery (webpack-internal:///./node_modules/apollo-client/bundle.esm.js:337:31)
    at eval (webpack-internal:///./node_modules/apollo-client/bundle.esm.js:257:19)
```

but data change well.

**Comment by guilhermewaess** [comment]
Sure, so the first definition (the one that you put inside apollo) shouldn't be a function.
here it is and simple example:
https://github.com/guilhermewaess/vue-gql/blob/c32e7971741d87028249b768f80ab135d9432eb3/client/src/components/posts/Posts.vue

**Comment by goodking-bq** [comment]
I've seen it befor ,but how to . if variables not a function ,inside  `this.pageSize` not define .
```js
variables: {
        limit: this.pageSize,
        offset: this.pageSize * (this.page - 1),
        filters: Object.keys(this.searchForm).map(item => {
          return {
            key: item.replace(/([A-Z])/g, "_$1").toLowerCase(),
            op: "contains",
            val: this.searchForm[item]
          };
        })
      },

vue-router.esm.js?8c4f:1924 TypeError: Cannot read property 'pageSize' of undefined
    at eval (index.vue?6ced:111)
    at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/SmartTable/index.vue?vue&type=script&lang=js& (1.js:23)
    at __webpack_require__ (app.js:767)
    at fn (app.js:130)
    at eval (index.vue?cbef:1)
    at Module../src/components/SmartTable/index.vue?vue&type=script&lang=js& (1.js:165)
    at __webpack_require__ (app.js:767)
    at fn (app.js:130)
    at eval (index.vue?358f:1)
    at Module../src/components/SmartTable/index.vue (1.js:153)
```

**Comment by goodking-bq** [comment]
> I've seen it befor ,but how to . if variables not a function ,inside `this.pageSize` not define .
> 
> ```js
> variables: {
>         limit: this.pageSize,
>         offset: this.pageSize * (this.page - 1),
>         filters: Object.keys(this.searchForm).map(item => {
>           return {
>             key: item.replace(/([A-Z])/g, "_$1").toLowerCase(),
>             op: "contains",
>             val: this.searchForm[item]
>           };
>         })
>       },
> 
> vue-router.esm.js?8c4f:1924 TypeError: Cannot read property 'pageSize' of undefined
>     at eval (index.vue?6ced:111)
>     at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/SmartTable/index.vue?vue&type=script&lang=js& (1.js:23)
>     at __webpack_require__ (app.js:767)
>     at fn (app.js:130)
>     at eval (index.vue?cbef:1)
>     at Module../src/components/SmartTable/index.vue?vue&type=script&lang=js& (1.js:165)
>     at __webpack_require__ (app.js:767)
>     at fn (app.js:130)
>     at eval (index.vue?358f:1)
>     at Module../src/components/SmartTable/index.vue (1.js:153)
> ```

i solve !! thanks @guilhermewaess

**Comment by guilhermewaess** [comment]
@goodking-bq cool :)

**Comment by flrnt** [comment]
@guilhermewaess @goodking-bq hi guys, I've followed your comments and I'm actually facing the same issue.
Basically, have a search input + load more btn, and then script is as follow  

```vue
<script>
import { ContentLoader } from 'vue-content-loader'
import gql from 'graphql-tag'
const LIMIT = 10

export default {
  components: {
    ContentLoader
  },
  apollo: {
    users: {
      query: gql`
        query SearchUsers($query: String!, $limit: Int!, $offset: Int!) {
          users(
            limit: $limit
            offset: $offset
            where: { fname: { _ilike: $query } }
          ) {
            fname
          }
        }
      `,
      variables: {
        query: `%${this.q}%`,
        limit: this.limit,
        offset: this.offset
      },
      skip() {
        return !this.q || this.q.length < 3
      },
      debounce: 200 // ms
    }
  },
  data() {
    return {
      limit: LIMIT,
      offset: 0,
      q: '',
      users: []
    }
  },
  computed: {
    resultsCount() {
      return this.users.length
    }
  },
  watch: {
    q(val) {
      if (val === '') {
        this.reset()
      }
    }
  },
  methods: {
    reset() {
      this.limit = LIMIT
      this.offset = 0
      this.q = ''
      this.users = []
    },
    fetchMore() {
      this.offset += this.limit
      this.$apollo.queries.users.fetchMore({
        variables() {
          return {
            limit: this.limit,
            offset: this.offset
          }
        },
        updateQuery: (previousResult, { fetchMoreResult }) => {
          return {
            __typename: 'users',
            users: [...previousResult.users, ...fetchMoreResult.users]
          }
        }
      })
    }
  }
}
</script>
```
@guilhermewaess as you mentionned, I change my first variables fn into object, but now I'm unable to use `this` inside.
How guys did you solve it ?

**Comment by guilhermewaess** [comment]
@flrnt I guess you have to remove the function:

https://github.com/guilhermewaess/vue-gql/blob/c32e7971741d87028249b768f80ab135d9432eb3/client/src/components/posts/Posts.vue

thats was the final working file on that project...its been a while wow

**Comment by thelinuxlich** [comment]
How do you dynamic variables(function) solving this?

**Comment by bryantbj** [comment]
@thelinuxlich and anyone else who may still be looking for a solution to this issue:

I came up with a solution for those that need to use both dynamic variables (function) AND `fetchMore`. It uses a combination of the `skip` property and the `created` hook. 

Imagine a component that needs a route param, `customerId`:

```javascript
import { ORDERS_QUERY } from "./Queries.js"

export default {
  apollo: {
    // +orders+ is some query which requires dynamic variables
    orders: {
      query: ORDERS_QUERY,
      // set +skip+ to true, without setting any variables.
      // This prevents the query from firing initially. We will manually
      // turn +skip+ off in the +created+ hook.
      skip: true
    }
  },

  data: () => ({
    page: 1
  }),

  computed: {
    variables() {
      return {
        page: this.page,
        // +customerId+ is a dynamic value not available when using an Object
        // rather than a function for apollo query variables
        customerId: this.$route.params.customerId
      }
    }
  },

  // in the +created+ hook, we can set the variables using our
  // computed property +variables+ and then turning +skip+ off
  created() {
    this.$apollo.queries.orders.setVariables({ ...this.variables });
    this.$apollo.queries.orders.skip = false;
  },

  methods: {
    incrementPage() {
       // increment the page/cursor/whatever else you need to change in your variables
       this.page++
    },
    fetchMore() {
      this.incrementPage()
      this.$apollo.queries.bins.fetchMore({
        variables: this.variables,
        updateQuery: (previousResult, { fetchMoreResult }) => {
          // handle the query update
        }
      })
    }
  }
}
```
